In [2]:
import pandas as pd
import numpy as np
from time import time

In [1]:
from google.cloud import bigquery

ModuleNotFoundError: No module named 'google'

In [3]:
# Load data to a pandas dataframe
df = pd.read_csv('df_chunk1.csv')

# Visualize top two records
df.head(5)

,Unnamed: 0,ID,Country,Vehicle_Family_ID,Pool,Manufacturer_EU,Manufacturer_OEM,Manufacturer_MS,TA_number,Type,...,Emission_reduction_IT,Emission_reduction_NEDC,Emission_reduction_WLTP,Deviation_factor,Verification_factor,Type_of_data,Registration_year,Registration_date,Fuel_consumption,Electric_range
0,0,57566673,IS,IP-01-JMB-2018-0001,RENAULT-NISSAN-MITSUBISHI,MITSUBISHI MOTORS CORPORATION,MITSUBISHI MOTORS CORPORATION,NaN,E1*2001/116*0406*32,CW0,...,NaN,NaN,NaN,NaN,NaN,P,2021,2021-03-24,NaN,45.0
1,1,57566674,IS,IP-01-JMB-2018-0001,RENAULT-NISSAN-MITSUBISHI,MITSUBISHI MOTORS CORPORATION,MITSUBISHI MOTORS CORPORATION,NaN,E1*2001/116*0406*32,CW0,...,NaN,NaN,NaN,NaN,NaN,P,2021,2021-03-24,NaN,45.0
2,2,57566675,IS,IP-01-JMB-2018-0001,RENAULT-NISSAN-MITSUBISHI,MITSUBISHI MOTORS CORPORATION,MITSUBISHI MOTORS CORPORATION,NaN,E1*2001/116*0406*32,CW0,...,NaN,NaN,NaN,NaN,NaN,P,2021,2021-03-23,NaN,45.0
3,3,57566676,IS,IP-01-JMB-2018-0001,RENAULT-NISSAN-MITSUBISHI,MITSUBISHI MOTORS CORPORATION,MITSUBISHI MOTORS CORPORATION,NaN,E1*2001/116*0406*32,CW0,...,NaN,NaN,NaN,NaN,NaN,P,2021,2021-03-23,NaN,45.0
4,4,57566677,IS,IP-01-JMB-2018-0001,RENAULT-NISSAN-MITSUBISHI,MITSUBISHI MOTORS CORPORATION,MITSUBISHI MOTORS CORPORATION,NaN,E1*2001/116*0406*32,CW0,...,NaN,NaN,NaN,NaN,NaN,P,2021,2021-03-19,NaN,45.0

In [6]:
#df.drop(columns='Unnamed: 0',inplace=True)

In [8]:
df.columns

Index(['ID', 'Country', 'Vehicle_Family_ID', 'Pool', 'Manufacturer_EU',
       'Manufacturer_OEM', 'Manufacturer_MS', 'TA_number', 'Type', 'Variant',
       'Version', 'Make', 'Commercial_Name', 'Category_A', 'Category_R',
       'Total_registrations', 'Mass_RO', 'WLTP_test_mass', 'Emissions_NEDC',
       'Emissions_WLTP', 'Wheel_base', 'Axle_width_steering',
       'Axle_width_other', 'Fuel_type', 'Fuel_mode', 'Engine_capacity',
       'Engine_power', 'Electricity_consumption', 'Emission_reduction_IT',
       'Emission_reduction_NEDC', 'Emission_reduction_WLTP',
       'Deviation_factor', 'Verification_factor', 'Type_of_data',
       'Registration_year', 'Registration_date', 'Fuel_consumption',
       'Electric_range'],
      dtype='object')

In [9]:
from sqlalchemy import create_engine

In [10]:
engine = create_engine('postgresql://root:root@localhost:5432/carbon')

In [11]:
%load_ext sql_magic
%config SQL.conn_name = 'engine'

In [12]:
print(pd.io.sql.get_schema(df, name='carbon', con=engine))

CREATE TABLE carbon (
	"ID" BIGINT,
	"Country" TEXT,
	"Vehicle_Family_ID" TEXT,
	"Pool" TEXT,
	"Manufacturer_EU" TEXT,
	"Manufacturer_OEM" TEXT,
	"Manufacturer_MS" FLOAT(53),
	"TA_number" TEXT,
	"Type" TEXT,
	"Variant" TEXT,
	"Version" TEXT,
	"Make" TEXT,
	"Commercial_Name" TEXT,
	"Category_A" TEXT,
	"Category_R" TEXT,
	"Total_registrations" BIGINT,
	"Mass_RO" FLOAT(53),
	"WLTP_test_mass" FLOAT(53),
	"Emissions_NEDC" FLOAT(53),
	"Emissions_WLTP" FLOAT(53),
	"Wheel_base" FLOAT(53),
	"Axle_width_steering" FLOAT(53),
	"Axle_width_other" FLOAT(53),
	"Fuel_type" TEXT,
	"Fuel_mode" TEXT,
	"Engine_capacity" FLOAT(53),
	"Engine_power" FLOAT(53),
	"Electricity_consumption" FLOAT(53),
	"Emission_reduction_IT" TEXT,
	"Emission_reduction_NEDC" FLOAT(53),
	"Emission_reduction_WLTP" FLOAT(53),
	"Deviation_factor" FLOAT(53),
	"Verification_factor" FLOAT(53),
	"Type_of_data" TEXT,
	"Registration_year" BIGINT,
	"Registration_date" TEXT,
	"Fuel_consumption" FLOAT(53),
	"Electric_range" FLOAT(53)
)

In [13]:
#Create table and specify columns
df.head(n=0).to_sql(name='emissions', con=engine, if_exists='replace')

0

In [14]:
df['Registration_date'] = pd.to_datetime(df['Registration_date'])

In [15]:
df.to_sql(name='emissions', con=engine, if_exists='append')

1000

In [24]:
%%read_sql df_result

select * from emissions where "Vehicle_Family_ID" is null

Query started at 03:07:11 PM UTC; Query executed in 0.00 m

,index,ID,Country,Vehicle_Family_ID,Pool,Manufacturer_EU,Manufacturer_OEM,Manufacturer_MS,TA_number,Type,...,Emission_reduction_IT,Emission_reduction_NEDC,Emission_reduction_WLTP,Deviation_factor,Verification_factor,Type_of_data,Registration_year,Registration_date,Fuel_consumption,Electric_range
0,151,57566824,IS,None,MERCEDES-BENZ,MERCEDES-BENZ AG,MERCEDES-BENZ AG,None,E1*2001/116*0480*41,204 X,...,None,None,NaN,None,None,P,2021,2021-08-13 00:00:00,NaN,43.0
1,153,57566826,IS,None,MERCEDES-BENZ,MERCEDES-BENZ AG,MERCEDES-BENZ AG,None,E1*2001/116*0480*41,204 X,...,None,None,NaN,None,None,P,2021,2021-07-23 00:00:00,NaN,27.0
2,156,57566829,IS,None,MERCEDES-BENZ,MERCEDES-BENZ AG,MERCEDES-BENZ AG,None,E1*2001/116*0480*41,204 X,...,None,None,NaN,None,None,P,2021,2021-06-11 00:00:00,NaN,43.0
3,158,57566831,IS,None,MERCEDES-BENZ,MERCEDES-BENZ AG,MERCEDES-BENZ AG,None,E1*2001/116*0480*41,204 X,...,None,None,NaN,None,None,P,2021,2021-05-28 00:00:00,NaN,43.0
4,159,57566832,IS,None,MERCEDES-BENZ,MERCEDES-BENZ AG,MERCEDES-BENZ AG,None,E1*2001/116*0480*41,204 X,...,None,None,NaN,None,None,P,2021,2021-05-28 00:00:00,NaN,43.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3018,99866,56658952,BE,None,VW-SAIC,AUDI AG,AUDI AG,None,E1*2007/46*1552*20,GA,...,e13 29,None,NaN,None,None,P,2021,2021-03-26 00:00:00,5.1,NaN
3019,99883,56658969,BE,None,VW-SAIC,AUDI AG,AUDI AG,None,E1*2007/46*1552*18,GA,...,None,None,NaN,None,None,P,2021,2021-02-25 00:00:00,NaN,NaN
3020,99921,56659007,BE,None,VW-SAIC,AUDI AG,AUDI AG,None,E1*2007/46*1552*15,GA,...,None,None,NaN,None,None,P,2021,2021-02-03 00:00:00,5.3,NaN
3021,99935,56659021,BE,None,VW-SAIC,AUDI AG,AUDI AG,None,E1*2007/46*1552*22,GA,...,None,None,NaN,None,None,P,2021,2021-06-28 00:00:00,NaN,NaN
3022,99999,56659085,BE,None,STELLANTIS,ALFA ROMEO,ALFA ROMEO SPA,None,E3*2007/46*0435*20,949,...,None,None,NaN,None,None,P,2021,2021-05-20 00:00:00,NaN,NaN

In [77]:
#read data iteratively with 200k chunks
df_iter = pd.read_csv('data.csv', iterator=True, chunksize=200000)

In [78]:
while True: 

    try:
        t_start = time()

        df = next(df_iter)
        
        df.rename(columns=cols, inplace =True)
        df['Registration_date'] = pd.to_datetime(df['Registration_date']) 
               

        df.to_sql(name='emissions', con=engine, if_exists='append')

        t_end = time()

        print('inserted another chunk, took %.3f second' % (t_end - t_start))

    except StopIteration:
        print("Finished ingesting data into the postgres database")
        break

DataError: (psycopg2.errors.InvalidTextRepresentation) invalid input syntax for type double precision: "E13 28"
LINE 1: ...565.0, 1565.0, 'PETROL', 'H', 1998.0, 90.0, NULL, 'E13 28', ...
                                                             ^

[SQL: INSERT INTO emissions (index, "ID", "Country", "Vehicle_Family_ID", "Pool", "Manufacturer_EU", "Manufacturer_OEM", "Manufacturer_MS", "TA_number", "Type", "Variant", "Version", "Make", "Commercial_Name", "Category_A", "Category_R", "Registrations", "Mass_RO", "WLTP_test_mass", "Emissions_NEDC", "Emissions_WLTP", "Wheel_base", "Axle_width_steering", "Axle_width_other", "Fuel_type", "Fuel_mode", "Engine_capacity", "Engine_power", "Electricity_consumption", "Emission_reduction_IT", "Emission_reduction_NEDC", "Emission_reduction_WLTP", "Deviation_factor", "Verification_factor", "Type_of_data", "Registration_year", "Registration_date", "Fuel_consumption", "Electric_range") VALUES (%(index)s, %(ID)s, %(Country)s, %(Vehicle_Family_ID)s, %(Pool)s, %(Manufacturer_EU)s, %(Manufacturer_OEM)s, %(Manufacturer_MS)s, %(TA_number)s, %(Type)s, %(Variant)s, %(Version)s, %(Make)s, %(Commercial_Name)s, %(Category_A)s, %(Category_R)s, %(Registrations)s, %(Mass_RO)s, %(WLTP_test_mass)s, %(Emissions_NEDC)s, %(Emissions_WLTP)s, %(Wheel_base)s, %(Axle_width_steering)s, %(Axle_width_other)s, %(Fuel_type)s, %(Fuel_mode)s, %(Engine_capacity)s, %(Engine_power)s, %(Electricity_consumption)s, %(Emission_reduction_IT)s, %(Emission_reduction_NEDC)s, %(Emission_reduction_WLTP)s, %(Deviation_factor)s, %(Verification_factor)s, %(Type_of_data)s, %(Registration_year)s, %(Registration_date)s, %(Fuel_consumption)s, %(Electric_range)s)]
[parameters: ({'index': 0, 'ID': 57566673, 'Country': 'IS', 'Vehicle_Family_ID': 'IP-01-JMB-2018-0001', 'Pool': 'RENAULT-NISSAN-MITSUBISHI', 'Manufacturer_EU': 'MITSUBISHI MOTORS CORPORATION', 'Manufacturer_OEM': 'MITSUBISHI MOTORS CORPORATION', 'Manufacturer_MS': None, 'TA_number': 'E1*2001/116*0406*32', 'Type': 'CW0', 'Variant': 'GGP21', 'Version': 'AVEJRRC5DAAA', 'Make': 'MITSUBISHI', 'Commercial_Name': 'Mitsubishi Outlander', 'Category_A': 'M1', 'Category_R': 'M1', 'Registrations': 1, 'Mass_RO': 1965.0, 'WLTP_test_mass': 2117.0, 'Emissions_NEDC': 40.0, 'Emissions_WLTP': 46.0, 'Wheel_base': 2670.0, 'Axle_width_steering': 1540.0, 'Axle_width_other': 1540.0, 'Fuel_type': 'PETROL/ELECTRIC', 'Fuel_mode': 'P', 'Engine_capacity': 2360.0, 'Engine_power': 99.0, 'Electricity_consumption': 169.0, 'Emission_reduction_IT': None, 'Emission_reduction_NEDC': None, 'Emission_reduction_WLTP': None, 'Deviation_factor': None, 'Verification_factor': None, 'Type_of_data': 'P', 'Registration_year': 2021, 'Registration_date': datetime.datetime(2021, 3, 24, 0, 0), 'Fuel_consumption': None, 'Electric_range': 45.0}, {'index': 1, 'ID': 57566674, 'Country': 'IS', 'Vehicle_Family_ID': 'IP-01-JMB-2018-0001', 'Pool': 'RENAULT-NISSAN-MITSUBISHI', 'Manufacturer_EU': 'MITSUBISHI MOTORS CORPORATION', 'Manufacturer_OEM': 'MITSUBISHI MOTORS CORPORATION', 'Manufacturer_MS': None, 'TA_number': 'E1*2001/116*0406*32', 'Type': 'CW0', 'Variant': 'GGP21', 'Version': 'AVEJRRC5DAAA', 'Make': 'MITSUBISHI', 'Commercial_Name': 'Mitsubishi Outlander', 'Category_A': 'M1', 'Category_R': 'M1', 'Registrations': 1, 'Mass_RO': 1965.0, 'WLTP_test_mass': 2117.0, 'Emissions_NEDC': 40.0, 'Emissions_WLTP': 46.0, 'Wheel_base': 2670.0, 'Axle_width_steering': 1540.0, 'Axle_width_other': 1540.0, 'Fuel_type': 'PETROL/ELECTRIC', 'Fuel_mode': 'P', 'Engine_capacity': 2360.0, 'Engine_power': 99.0, 'Electricity_consumption': 169.0, 'Emission_reduction_IT': None, 'Emission_reduction_NEDC': None, 'Emission_reduction_WLTP': None, 'Deviation_factor': None, 'Verification_factor': None, 'Type_of_data': 'P', 'Registration_year': 2021, 'Registration_date': datetime.datetime(2021, 3, 24, 0, 0), 'Fuel_consumption': None, 'Electric_range': 45.0}, {'index': 2, 'ID': 57566675, 'Country': 'IS', 'Vehicle_Family_ID': 'IP-01-JMB-2018-0001', 'Pool': 'RENAULT-NISSAN-MITSUBISHI', 'Manufacturer_EU': 'MITSUBISHI MOTORS CORPORATION', 'Manufacturer_OEM': 'MITSUBISHI MOTORS CORPORATION', 'Manufacturer_MS': None, 'TA_number': 'E1*2001/116*0406*32', 'Type': 'CW0', 'Variant': 'GGP21', 'Version': 'AVEJRRC5DAAA', 'Make': 'MITSUBISHI', 'Commercial_Name': 'Mitsubishi Outlander', 'Category_A': 'M1', 'Category_R': 'M1', 'Registrations': 1, 'Mass_RO': 1965.0, 'WLTP_test_mass': 2117.0, 'Emissions_NEDC': 40.0, 'Emissions_WLTP': 46.0, 'Wheel_base': 2670.0, 'Axle_width_steering': 1540.0, 'Axle_width_other': 1540.0, 'Fuel_type': 'PETROL/ELECTRIC', 'Fuel_mode': 'P', 'Engine_capacity': 2360.0, 'Engine_power': 99.0, 'Electricity_consumption': 169.0, 'Emission_reduction_IT': None, 'Emission_reduction_NEDC': None, 'Emission_reduction_WLTP': None, 'Deviation_factor': None, 'Verification_factor': None, 'Type_of_data': 'P', 'Registration_year': 2021, 'Registration_date': datetime.datetime(2021, 3, 23, 0, 0), 'Fuel_consumption': None, 'Electric_range': 45.0}, {'index': 3, 'ID': 57566676, 'Country': 'IS', 'Vehicle_Family_ID': 'IP-01-JMB-2018-0001', 'Pool': 'RENAULT-NISSAN-MITSUBISHI', 'Manufacturer_EU': 'MITSUBISHI MOTORS CORPORATION', 'Manufacturer_OEM': 'MITSUBISHI MOTORS CORPORATION', 'Manufacturer_MS': None, 'TA_number': 'E1*2001/116*0406*32', 'Type': 'CW0', 'Variant': 'GGP21', 'Version': 'AVEJRRC5DAAA', 'Make': 'MITSUBISHI', 'Commercial_Name': 'Mitsubishi Outlander', 'Category_A': 'M1', 'Category_R': 'M1', 'Registrations': 1, 'Mass_RO': 1965.0, 'WLTP_test_mass': 2117.0, 'Emissions_NEDC': 40.0, 'Emissions_WLTP': 46.0, 'Wheel_base': 2670.0, 'Axle_width_steering': 1540.0, 'Axle_width_other': 1540.0, 'Fuel_type': 'PETROL/ELECTRIC', 'Fuel_mode': 'P', 'Engine_capacity': 2360.0, 'Engine_power': 99.0, 'Electricity_consumption': 169.0, 'Emission_reduction_IT': None, 'Emission_reduction_NEDC': None, 'Emission_reduction_WLTP': None, 'Deviation_factor': None, 'Verification_factor': None, 'Type_of_data': 'P', 'Registration_year': 2021, 'Registration_date': datetime.datetime(2021, 3, 23, 0, 0), 'Fuel_consumption': None, 'Electric_range': 45.0}, {'index': 4, 'ID': 57566677, 'Country': 'IS', 'Vehicle_Family_ID': 'IP-01-JMB-2018-0001', 'Pool': 'RENAULT-NISSAN-MITSUBISHI', 'Manufacturer_EU': 'MITSUBISHI MOTORS CORPORATION', 'Manufacturer_OEM': 'MITSUBISHI MOTORS CORPORATION', 'Manufacturer_MS': None, 'TA_number': 'E1*2001/116*0406*32', 'Type': 'CW0', 'Variant': 'GGP21', 'Version': 'AVEJRRC5DAAA', 'Make': 'MITSUBISHI', 'Commercial_Name': 'Mitsubishi Outlander', 'Category_A': 'M1', 'Category_R': 'M1', 'Registrations': 1, 'Mass_RO': 1965.0, 'WLTP_test_mass': 2117.0, 'Emissions_NEDC': 40.0, 'Emissions_WLTP': 46.0, 'Wheel_base': 2670.0, 'Axle_width_steering': 1540.0, 'Axle_width_other': 1540.0, 'Fuel_type': 'PETROL/ELECTRIC', 'Fuel_mode': 'P', 'Engine_capacity': 2360.0, 'Engine_power': 99.0, 'Electricity_consumption': 169.0, 'Emission_reduction_IT': None, 'Emission_reduction_NEDC': None, 'Emission_reduction_WLTP': None, 'Deviation_factor': None, 'Verification_factor': None, 'Type_of_data': 'P', 'Registration_year': 2021, 'Registration_date': datetime.datetime(2021, 3, 19, 0, 0), 'Fuel_consumption': None, 'Electric_range': 45.0}, {'index': 5, 'ID': 57566678, 'Country': 'IS', 'Vehicle_Family_ID': 'IP-01-JMB-2018-0001', 'Pool': 'RENAULT-NISSAN-MITSUBISHI', 'Manufacturer_EU': 'MITSUBISHI MOTORS CORPORATION', 'Manufacturer_OEM': 'MITSUBISHI MOTORS CORPORATION', 'Manufacturer_MS': None, 'TA_number': 'E1*2001/116*0406*32', 'Type': 'CW0', 'Variant': 'GGP21', 'Version': 'AVEJRRC5DAAA', 'Make': 'MITSUBISHI', 'Commercial_Name': 'Mitsubishi Outlander', 'Category_A': 'M1', 'Category_R': 'M1', 'Registrations': 1, 'Mass_RO': 1965.0, 'WLTP_test_mass': 2117.0, 'Emissions_NEDC': 40.0, 'Emissions_WLTP': 46.0, 'Wheel_base': 2670.0, 'Axle_width_steering': 1540.0, 'Axle_width_other': 1540.0, 'Fuel_type': 'PETROL/ELECTRIC', 'Fuel_mode': 'P', 'Engine_capacity': 2360.0, 'Engine_power': 99.0, 'Electricity_consumption': 169.0, 'Emission_reduction_IT': None, 'Emission_reduction_NEDC': None, 'Emission_reduction_WLTP': None, 'Deviation_factor': None, 'Verification_factor': None, 'Type_of_data': 'P', 'Registration_year': 2021, 'Registration_date': datetime.datetime(2021, 3, 16, 0, 0), 'Fuel_consumption': None, 'Electric_range': 45.0}, {'index': 6, 'ID': 57566679, 'Country': 'IS', 'Vehicle_Family_ID': 'IP-01-JMB-2018-0001', 'Pool': 'RENAULT-NISSAN-MITSUBISHI', 'Manufacturer_EU': 'MITSUBISHI MOTORS CORPORATION', 'Manufacturer_OEM': 'MITSUBISHI MOTORS CORPORATION', 'Manufacturer_MS': None, 'TA_number': 'E1*2001/116*0406*32', 'Type': 'CW0', 'Variant': 'GGP21', 'Version': 'AVEJRRC5DAAA', 'Make': 'MITSUBISHI', 'Commercial_Name': 'Mitsubishi Outlander', 'Category_A': 'M1', 'Category_R': 'M1', 'Registrations': 1, 'Mass_RO': 1965.0, 'WLTP_test_mass': 2117.0, 'Emissions_NEDC': 40.0, 'Emissions_WLTP': 46.0, 'Wheel_base': 2670.0, 'Axle_width_steering': 1540.0, 'Axle_width_other': 1540.0, 'Fuel_type': 'PETROL/ELECTRIC', 'Fuel_mode': 'P', 'Engine_capacity': 2360.0, 'Engine_power': 99.0, 'Electricity_consumption': 169.0, 'Emission_reduction_IT': None, 'Emission_reduction_NEDC': None, 'Emission_reduction_WLTP': None, 'Deviation_factor': None, 'Verification_factor': None, 'Type_of_data': 'P', 'Registration_year': 2021, 'Registration_date': datetime.datetime(2021, 3, 16, 0, 0), 'Fuel_consumption': None, 'Electric_range': 45.0}, {'index': 7, 'ID': 57566680, 'Country': 'IS', 'Vehicle_Family_ID': 'IP-01-JMB-2018-0001', 'Pool': 'RENAULT-NISSAN-MITSUBISHI', 'Manufacturer_EU': 'MITSUBISHI MOTORS CORPORATION', 'Manufacturer_OEM': 'MITSUBISHI MOTORS CORPORATION', 'Manufacturer_MS': None, 'TA_number': 'E1*2001/116*0406*32', 'Type': 'CW0', 'Variant': 'GGP21', 'Version': 'AVEJRRC5DAAA', 'Make': 'MITSUBISHI', 'Commercial_Name': 'Mitsubishi Outlander', 'Category_A': 'M1', 'Category_R': 'M1', 'Registrations': 1, 'Mass_RO': 1965.0, 'WLTP_test_mass': 2117.0, 'Emissions_NEDC': 40.0, 'Emissions_WLTP': 46.0, 'Wheel_base': 2670.0, 'Axle_width_steering': 1540.0, 'Axle_width_other': 1540.0, 'Fuel_type': 'PETROL/ELECTRIC', 'Fuel_mode': 'P', 'Engine_capacity': 2360.0, 'Engine_power': 99.0, 'Electricity_consumption': 169.0, 'Emission_reduction_IT': None, 'Emission_reduction_NEDC': None, 'Emission_reduction_WLTP': None, 'Deviation_factor': None, 'Verification_factor': None, 'Type_of_data': 'P', 'Registration_year': 2021, 'Registration_date': datetime.datetime(2021, 3, 15, 0, 0), 'Fuel_consumption': None, 'Electric_range': 45.0}  ... displaying 10 of 200000 total bound parameter sets ...  {'index': 199998, 'ID': 56509157, 'Country': 'BE', 'Vehicle_Family_ID': 'IP-0500705-TMA-1', 'Pool': 'HYUNDAI', 'Manufacturer_EU': 'HYUNDAI CZECH', 'Manufacturer_OEM': 'HYUNDAI MOTOR MANUFACTURING CZECH SRO', 'Manufacturer_MS': None, 'TA_number': 'E5*2018/858*00001*00', 'Type': 'NX4E', 'Variant': 'F5P21', 'Version': 'M61A14', 'Make': 'HYUNDAI', 'Commercial_Name': 'Hyundai TUCSON ix35', 'Category_A': 'M1', 'Category_R': 'M1', 'Registrations': 1, 'Mass_RO': 1538.0, 'WLTP_test_mass': 1674.0, 'Emissions_NEDC': None, 'Emissions_WLTP': 149.0, 'Wheel_base': 2680.0, 'Axle_width_steering': 1615.0, 'Axle_width_other': 1622.0, 'Fuel_type': 'PETROL', 'Fuel_mode': 'H', 'Engine_capacity': 1598.0, 'Engine_power': None, 'Electricity_consumption': None, 'Emission_reduction_IT': None, 'Emission_reduction_NEDC': None, 'Emission_reduction_WLTP': None, 'Deviation_factor': None, 'Verification_factor': None, 'Type_of_data': 'P', 'Registration_year': 2021, 'Registration_date': datetime.datetime(2021, 7, 15, 0, 0), 'Fuel_consumption': 5.8, 'Electric_range': None}, {'index': 199999, 'ID': 56509158, 'Country': 'BE', 'Vehicle_Family_ID': 'IP-0500705-TMA-1', 'Pool': 'HYUNDAI', 'Manufacturer_EU': 'HYUNDAI CZECH', 'Manufacturer_OEM': 'HYUNDAI MOTOR MANUFACTURING CZECH SRO', 'Manufacturer_MS': None, 'TA_number': 'E5*2018/858*00001*00', 'Type': 'NX4E', 'Variant': 'F5P21', 'Version': 'M61A14', 'Make': 'HYUNDAI', 'Commercial_Name': 'Hyundai TUCSON ix35', 'Category_A': 'M1', 'Category_R': 'M1', 'Registrations': 1, 'Mass_RO': 1538.0, 'WLTP_test_mass': 1674.0, 'Emissions_NEDC': None, 'Emissions_WLTP': 149.0, 'Wheel_base': 2680.0, 'Axle_width_steering': 1615.0, 'Axle_width_other': 1622.0, 'Fuel_type': 'PETROL', 'Fuel_mode': 'H', 'Engine_capacity': 1598.0, 'Engine_power': None, 'Electricity_consumption': None, 'Emission_reduction_IT': None, 'Emission_reduction_NEDC': None, 'Emission_reduction_WLTP': None, 'Deviation_factor': None, 'Verification_factor': None, 'Type_of_data': 'P', 'Registration_year': 2021, 'Registration_date': datetime.datetime(2021, 2, 4, 0, 0), 'Fuel_consumption': 5.8, 'Electric_range': None})]
(Background on this error at: https://sqlalche.me/e/14/9h9h)